version: "3.8"
services:
  proxy:
      container_name: codeigniter-fullstack-starter-kit-proxy
      image: jwilder/nginx-proxy
      ports:
          - "10:80"
          - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

  codeigniter-fullstack-starter-kit:
    build:
      args:
        user: holoog
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: holoog/codeigniter-fullstack-starter-kit
    container_name: codeigniter-fullstack-starter-kit
    restart: unless-stopped
    volumes:
      - "./:/var/www/html"
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    environment:
      - database.default.hostname=codeigniter-fullstack-starter-kit-db
      - database.default.database=db-codeigniter-fullstack-starter-kit
      - database.default.username=db-codeigniter-fullstack-starter-kit-user
      - database.default.password=secret
      - database.default.DBDriver=MySQLi
    depends_on:
      - database
    ports:
      - "2525:80"
    networks:
      - codeigniter-fullstack-starter-kit

  nginx:
    image: nginx:1.18-alpine
    restart: unless-stopped
    ports:
      - 2526:80
    volumes:
      - "./:/var/www/html"
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - database
      - codeigniter-fullstack-starter-kit
    networks:
      - codeigniter-fullstack-starter-kit

  codeigniter-fullstack-starter-kit-phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "2527:80"
    environment:
      - PMA_HOST=codeigniter-fullstack-starter-kit-db
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: codeigniter-fullstack-starter-kit-phpmyadmin
    networks:
      - codeigniter-fullstack-starter-kit

  database:
    image: mysql:5.7
    container_name: codeigniter-fullstack-starter-kit-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db-codeigniter-fullstack-starter-kit
      - MYSQL_USER=db-codeigniter-fullstack-starter-kit-user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "2528:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    networks:
      - codeigniter-fullstack-starter-kit

networks:
  codeigniter-fullstack-starter-kit:
    driver: bridge
